create table TAI_KHOAN
(
USERNAME VARCHAR(30),
PASSWORD VARCHAR(30) NOT NULL,
LOAI_TAI_KHOAN VARCHAR(15) NOT NULL,
PRIMARY KEY(USERNAME)
);

INSERT INTO TAI_KHOAN VALUES ('Admin_1','Nhom3','Admin');
INSERT INTO TAI_KHOAN VALUES ('Admin_2','Nhom3','Admin');
INSERT INTO TAI_KHOAN VALUES ('TeamManager_Eng','Nhom3','TeamManager');
INSERT INTO TAI_KHOAN VALUES ('TeamManager_Ned','Nhom3','TeamManager');
INSERT INTO TAI_KHOAN VALUES ('TeamManager_Bra','Nhom3','TeamManager');
INSERT INTO TAI_KHOAN VALUES ('TeamManager_Spa','Nhom3','TeamManager');
INSERT INTO TAI_KHOAN VALUES ('nhabao_1','Nhom3','Reporter');
INSERT INTO TAI_KHOAN VALUES ('nhabao_2','Nhom3','Reporter');
INSERT INTO TAI_KHOAN VALUES ('nhabao_3','Nhom3','Reporter');
INSERT INTO TAI_KHOAN VALUES ('nhabao_4','Nhom3','Reporter');
INSERT INTO TAI_KHOAN VALUES ('client_1','Nhom3','Client');
INSERT INTO TAI_KHOAN VALUES ('client_2','Nhom3','Client');
INSERT INTO TAI_KHOAN VALUES ('client_3','Nhom3','Client');
INSERT INTO TAI_KHOAN VALUES ('client_4','Nhom3','Client');

create table QUAN_LY_DOI_BONG 
(
USERNAME VARCHAR(30),
ID_DOI_TUYEN CHAR(5) CHECK (REGEXP_LIKE(ID_DOI_TUYEN,'DT[0-9]{3}')),
PRIMARY KEY (USERNAME,ID_DOI_TUYEN),
FOREIGN KEY (USERNAME) REFERENCES TAI_KHOAN(USERNAME),
FOREIGN KEY (ID_DOI_TUYEN) REFERENCES DOI_TUYEN(ID)
);

INSERT INTO QUAN_LY_DOI_BONG VALUES ('TeamManager_Eng','DT001');
INSERT INTO QUAN_LY_DOI_BONG VALUES ('TeamManager_Ned','DT002');
INSERT INTO QUAN_LY_DOI_BONG VALUES ('TeamManager_Bra','DT003');
INSERT INTO QUAN_LY_DOI_BONG VALUES ('TeamManager_Spa','DT004');

create table BINH_LUAN
(
ID_TRAN_DAU CHAR(7)     CHECK (REGEXP_LIKE(ID_TRAN_DAU,'TD[0-9]{5}')),
USERNAME VARCHAR(30),
THOI_DIEM  TIMESTAMP,
NOI_DUNG VARCHAR(4000),
DUYET CHAR CHECK(DUYET IN('Y','N','-')),
PRIMARY KEY (ID_TRAN_DAU, USERNAME, THOI_DIEM),
FOREIGN KEY (ID_TRAN_DAU) REFERENCES TRAN_DAU(ID),
FOREIGN KEY (USERNAME) REFERENCES TAI_KHOAN(USERNAME)
);
